apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp-frontend
spec:
  selector:
    matchLabels:
      app: react-webapp
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: react-webapp
        tier: frontend
        track: stable
    spec:
      containers:
      - name: react-webapp
        image: famasboy888/react-app:0.0.4.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080